import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { Hind_Siliguri } from 'next/font/google';
import { Providers } from "./providers";

const hindSiliguri = Hind_Siliguri({
  subsets: ['bengali', 'latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "ফসলবাড়ি",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn" className="h-full antialiased" suppressHydrationWarning>
      <body className={`${hindSiliguri.className} min-h-full flex flex-col`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}