import type { Metadata } from "next";
import "./globals.css";
import { Hind_Siliguri, Manrope } from 'next/font/google'
import "./globals.css";
import { Providers } from "./providers";
import { Suspense } from "react";
import { LoadingProvider, HarvestLoader } from "@/Components/loading";
import LayoutShell from "@/Components/LayoutShell";

const manrope = Manrope({ subsets: ['latin'], variable: '--font-sans' })
const hindSiliguri = Hind_Siliguri({
  subsets: ['bengali', 'latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-bengali',
})

export const metadata: Metadata = {
  title: "ফসলবাড়ি",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn" className="h-full antialiased" suppressHydrationWarning>
      <body className={`${hindSiliguri.variable} ${manrope.variable} ${hindSiliguri.className} min-h-full flex flex-col`}>
        <Providers>
          <Suspense fallback={<HarvestLoader variant="fallback" />}>
            <LoadingProvider>
              <LayoutShell>
                {children}
              </LayoutShell>
            </LoadingProvider>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}